default:
  paths:
    home_dir:  "E:/SDSU_GEOG"
    data_dir: "E:/SDSU_GEOG/Thesis/Data"
    input:
      signatures: "/Thesis/Data/Signatures/sigs_camels_v2.csv"
      attributes: "/RandomForest_R/inputs/camels_attribs_v2.csv"
    output:
      predictions: "/RandomForest_R/outputs_final/caravan_geol_giw_predicted_signatures.csv"
      importance: "/RandomForest_R/outputs_final/caravan_geol_giw_var_importance.csv"
      rsquared: "/RandomForest_R/outputs_final/caravan_geol_giw_r_squared.csv"
  settings:
    seed: 0
    ntree: 500
  sigs_predict:
    - gauge_id
    - TotalRR
    - RR_Seasonality
    - EventRR
    - Recession_a_Seasonality
    - AverageStorage
    - RecessionParameters_1
    - RecessionParameters_2
    - First_Recession_Slope
    - Mid_Recession_Slope
    - EventRR_TotalRR_ratio
    - VariabilityIndex
    - BFI
    - BaseflowRecessionK