paths:
  home_dir: /home/raraki/data/signature-prediction
  out_dir: /out/rf
  train:
    signatures: /signatures/caravan_us_20250223_withWu/out_calc_All_custom_filt_qc_snow_gages2subset.csv
    attributes: /derived_attrs/assembled_RA/attrs_cara_and_gages2+climate_morph_epa.csv
  test:
    attributes: /derived_attrs/assembled_RA/attrs_cara_and_gages2+climate_morph_epa.csv
experiment_name: climattrs_peakSWEdivP
filter_by_ecoregion:
  run: false
  name: NA
settings:
  seed: 0
  ntree: 500
  num_folds: 10
  eval_metric: MSE
parallel:
  nCores: 16
sigs_predict:
- TotalRR
- RR_Seasonality
- EventRR
- Recession_a_Seasonality
- AverageStorage
- RecessionParameters_b
- RecessionParameters_T0
- First_Recession_Slope
- Mid_Recession_Slope
- EventRR_TotalRR_ratio
- VariabilityIndex
- BFI
- BaseflowRecessionK
- IE_thresh_signif
- SE_thresh_signif
- Storage_thresh_signif
- IE_thresh
- SE_thresh
- IE_effect
- SE_effect
- Storage_thresh
- SE_slope
- R_Pvol_RC
- R_Pint_RC
attrs_of_interest:
- ELEV_MEAN_M_BASIN
- DRAIN_SQKM
- SLOPE_PCT
- FORESTNLCD06
- CROPSNLCD06
- PASTURENLCD06
- PCT_IRRIG_AG
- SNOWICENLCD06
- pac_pc_sse
- isowet_areafrac
- CLAYAVE
- SILTAVE
- OMAVE
- kar_pc_sse
- geol_weighted_ave_age_ma
- PDEN_2000_BLOCK
- gdp_ud_sav
- DEVNLCD06
- PPTAVG_BASIN
- PET
- aridity
- SNOW_PCT_PRECIP
- PRECIP_SEAS_IND
- high_prec_freq
- low_prec_freq
- low_prec_dur
- peakSWEdivP