paths:
  home_dir: /home/raraki/data/signature-prediction
  out_dir: /out/rf
  train:
    signatures: /signatures/caravan_us_20250525/out_calc_All_custom_filt_qc_snow_area.csv
    attributes: /derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517+cluster.csv
  test:
    attributes: /derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517+cluster.csv
experiment_name: cluster_0
filter_by_cluster:
  run: true
  name: 0
settings:
  seed: 0
  ntree: 500
  num_folds: 10
  eval_metric: MSE
save_models: false
parallel:
  nCores: 16
sigs_predict:
- TotalRR
- RR_Seasonality
- EventRR
- Recession_a_Seasonality
- AverageStorage
- RecessionParameters_b
- RecessionParameters_T0
- First_Recession_Slope
- Mid_Recession_Slope
- EventRR_TotalRR_ratio
- VariabilityIndex
- BFI
- BaseflowRecessionK
- IE_thresh_signif
- SE_thresh_signif
- Storage_thresh_signif
- IE_thresh
- SE_thresh
- IE_effect
- SE_effect
- Storage_thresh
- SE_slope
- R_Pvol_RC
- R_Pint_RC
attrs_of_interest:
- ELEV_MEAN_M_BASIN
- DRAIN_SQKM
- SLOPE_DEG_x10
- FORESTNLCD06
- CROPSNLCD06
- PASTURENLCD06
- PCT_IRRIG_AG
- SNOWICENLCD06
- PADCAT1_AND_2
- isowet_areafrac
- CLAYAVE
- SILTAVE
- soc_th_sav
- kar_pc_sse
- geol_weighted_ave_age_ma
- PDEN_2000_BLOCK
- gdp_ud_sav
- hdi_ix_sav
- P_mm_day
- PET_mm_day
- ARIDITY_GAGES2
- SNOW_FRAC_PRECIP
- seasonality_FAO_PM
- high_prec_freq
- low_prec_freq
- low_prec_dur
