paths:
  home_dir: /home/raraki/data/signature-prediction
  out_dir: /out/rf
  train:
    signatures: /signatures/gages2_caravan_us_20250219/out_calc_All_custom_filt_qc_caravanoverlap.csv
    attributes: /derived_attrs/assembled_RA/attrs_gages2+climate_hammond.csv
  test:
    attributes: /derived_attrs/assembled_RA/attrs_gages2+climate_hammond.csv
experiment_name: gages2exp_bestattrs_and_surfacewater
filter_by_ecoregion:
  run: false
  name: NA
settings:
  seed: 0
  ntree: 500
  num_folds: 10
  eval_metric: MSE
parallel:
  nCores: 16
sigs_predict:
- TotalRR
- RR_Seasonality
- EventRR
- Recession_a_Seasonality
- AverageStorage
- RecessionParameters_b
- RecessionParameters_T0
- First_Recession_Slope
- Mid_Recession_Slope
- EventRR_TotalRR_ratio
- VariabilityIndex
- BFI
- BaseflowRecessionK
- IE_thresh_signif
- SE_thresh_signif
- Storage_thresh_signif
- IE_thresh
- SE_thresh
- IE_effect
- SE_effect
- Storage_thresh
- SE_slope
attrs_of_interest:
- DRAIN_SQKM
- BAS_COMPACTNESS
- PPTAVG_BASIN
- T_AVG_BASIN
- RH_BASIN
- WD_BASIN
- PRECIP_SEAS_IND
- STREAMS_KM_SQ_KM
- MAINSTEM_SINUOUSITY
- ARTIFPATH_PCT
- ARTIFPATH_MAINSTEM_PCT
- TOPWET
- PCT_1ST_ORDER
- PCT_6TH_ORDER_OR_MORE
- PCT_NO_ORDER
- CANALS_PCT
- CANALS_MAINSTEM_PCT
- FRESHW_WITHDRAWAL
- PCT_IRRIG_AG
- FRAGUN_BASIN
- HIRES_LENTIC_DENS
- HIRES_LENTIC_MEANSIZ
- DEVNLCD06
- FORESTNLCD06
- PLANTNLCD06
- WATERNLCD06
- SNOWICENLCD06
- BARRENNLCD06
- DECIDNLCD06
- EVERGRNLCD06
- MIXEDFORNLCD06
- SHRUBNLCD06
- GRASSNLCD06
- WOODYWETNLCD06
- EMERGWETNLCD06
- HGA
- HGB
- HGAD
- HGC
- HGD
- HGAC
- HGBD
- HGCD
- HGBC
- HGVAR
- OMAVE
- WTDEPAVE
- ROCKDEPAVE
- CLAYAVE
- SILTAVE
- SANDAVE
- RRMEAN
- ASPECT_NORTHNESS
- ASPECT_EASTNESS
- PADCAT1_PCT_BASIN
- PADCAT2_PCT_BASIN
- PADCAT3_PCT_BASIN
- input_seasonality
- input_PET_synchrony
