paths:
  home_dir: /home/raraki/data/signature-prediction
  out_dir: /out/rf
  train:
    signatures: /signatures/caravan_us_20260716/out_calc_All_custom_filt_qc_snow_area.csv
    attributes: /derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517+cluster.csv
  test:
    attributes: /derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517+cluster.csv
experiment_name: test
filter_by_cluster: 
  run: true
  name: 1
settings:
  seed: 0
  ntree: 100
  num_folds: 3
  eval_metric: RMSE
  # "MSE", "RMSE" etc.. 
parallel:
  nCores: 16
sigs_predict:
- TotalRR
- BFI
attrs_of_interest:
- ele_mt_sav
- area
- sgr_dk_sav
- for_pc_sse
- crp_pc_sse
- pst_pc_sse
- ire_pc_sse