paths:
  home_dir:  "G:/Shared drives/Signatures -- large scale/baseflow"
  out_dir: "RAraki/out/rf"
  train:
    signatures: "RAraki/out/signatures/caravan_camels_20240530_defaultparams/out_calc_All.csv" # "RAraki/out/signatures/sig_camels_v2_aholt.csv"
    attributes: "AHolt/data/derived_attrs/assembled_RA/attrs_camels_original.csv"
  test:
    attributes: "AHolt/data/derived_attrs/assembled_RA/attrs_camels_original.csv"
experiment_name: "reproduce_aholt_usingCaravanDerivedSigs" #"reproduce_aholt"
settings:
  seed: 42
  ntree: 500
  num_folds: 10
  eval_metric: "MSE"
parallel:
  nCores: 4
sigs_predict:
  - TotalRR
  - RR_Seasonality
  - EventRR
  - Recession_a_Seasonality
  - AverageStorage
  - RecessionParameters_1
  - RecessionParameters_2
  # - RecessionParameters_b
  # - RecessionParameters_T0
  - First_Recession_Slope
  - Mid_Recession_Slope
  - EventRR_TotalRR_ratio
  - VariabilityIndex
  - BFI
  - BaseflowRecessionK
attrs_of_interest:
  - p_seasonality
  - frac_snow
  - aridity
  - low_prec_freq
  - low_prec_dur
  - elev_mean
  - slope_mean
  - area_gages2
  - frac_forest
  - root_depth_50
  - root_depth_99
  - soil_depth_statsgo
  - max_water_content
  - sand_frac
  - silt_frac
  - clay_frac
  - other_frac
  - carbonate_rocks_frac
  - geol_porostiy
  - geol_permeability
  - geol_weighted_ave_age_ma
  - isowet_areafrac
