paths:
  home_dir: "G:/Shared drives/Signatures -- large scale/baseflow"
  out_dir: "RAraki/out/rf"
  predict:
    model_dir: "RAraki/out/rf/output_raraki_20250826_cluster_all"
    attributes: "RAraki/data/Caravan_attrs_gages2/attributes_to_pred_forRF_psudo_name.csv"
experiment_name: "pred_gg2_only"
parallel:
  nCores: 16
sigs_predict:
- TotalRR
- EventRR
- Recession_a_Seasonality
- AverageStorage
- RecessionParameters_b
- VariabilityIndex
- BFI
- BaseflowRecessionK
- IE_thresh_signif
- SE_thresh_signif
- IE_thresh
- SE_thresh
attrs_of_interest:
- ELEV_MEAN_M_BASIN
- DRAIN_SQKM
- SLOPE_DEG_x10
- FORESTNLCD06
- CROPSNLCD06
- PASTURENLCD06
- PCT_IRRIG_AG
- PADCAT1_AND_2
- isowet_areafrac
- CLAYAVE
- SILTAVE
- soc_th_sav
- kar_pc_sse
- geol_weighted_ave_age_ma
- PDEN_2000_BLOCK
- P_mm_day
- PET_mm_day
- ARIDITY_GAGES2
- SNOW_FRAC_PRECIP
- seasonality_FAO_PM
- high_prec_freq
- low_prec_freq
- low_prec_dur