paths:
  home_dir: G:/Shared drives/Signatures -- large scale/baseflow
  out_dir: RAraki/out/rf
  train:
    signatures: RAraki/out/signatures/caravan_us_20250223_withWu/out_calc_All_custom_filt_qc_snow_area_subset_gages2.csv
    attributes: RAraki/data/derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517.csv
  test:
    attributes: RAraki/data/derived_attrs/assembled_RA/attrs_cara_gages2_etc_20250517.csv
experiment_name: 20250517_gages2_subset
filter_by_cluster:
  run: false
  name: NA
settings:
  seed: 0
  ntree: 10 # for testing
  num_folds: 3 # for testing
  eval_metric: MSE
parallel:
  nCores: 2
sigs_predict:
- TotalRR
- RR_Seasonality
# - EventRR
# - Recession_a_Seasonality
# - AverageStorage
# - RecessionParameters_b
# - RecessionParameters_T0
# - First_Recession_Slope
# - Mid_Recession_Slope
# - EventRR_TotalRR_ratio
# - VariabilityIndex
# - BFI
# - BaseflowRecessionK
# - IE_thresh_signif
# - SE_thresh_signif
# - Storage_thresh_signif
# - IE_thresh
# - SE_thresh
# - IE_effect
# - SE_effect
# - Storage_thresh
# - SE_slope
# - R_Pvol_RC
# - R_Pint_RC
attrs_of_interest:
- ele_mt_sav
- area
- slp_dg_sav
- for_pc_sse
- crp_pc_sse
- pst_pc_sse
- ire_pc_sse
- prm_pc_sse
- pac_pc_sse
- isowet_areafrac
- cly_pc_sav
- slt_pc_sav
- soc_th_sav
- kar_pc_sse
- geol_weighted_ave_age_ma
- ppd_pk_sav
- gdp_ud_sav
- hdi_ix_sav
- p_mean
- pet_mean_FAO_PM
- aridity_FAO_PM
- frac_snow
- seasonality_FAO_PM
- high_prec_freq
- low_prec_freq
- low_prec_dur