paths:
  home_dir: "G:/Shared drives/Signatures -- large scale/baseflow"
  # On Google Drive: G:/Shared drives/Signatures -- large scale/baseflow
  # On UCSB server: /home/raraki/data/signature-prediction
  out_dir: "RAraki/out/rf"
  # On Google Drive: RAraki/out/rf
  # On UCSB server: /out/rf
  train:
    signatures: "RAraki/out/signatures/caravan_camels_20240609_tunedparams/out_calc_ALL_custom.csv"
    # On Google Drive: "RAraki/out/signatures/caravan_camels_20240609_tunedparams/out_calc_ALL_custom.csv"
    # On UCSB server: "/signatures/caravan_camels_20240609_tunedparams/out_calc_ALL_custom.csv"
    attributes: "RAraki/data/derived_attrs/assembled_RA/attrs_cara_and_gages2+climate+morph+padcat+cluster.csv"
    # On Google Drive: "RAraki/data/derived_attrs/assembled_RA/attrs_camels.csv"
    # On UCSB server: "/derived_attrs/assembled_RA/attrs_camels.csv"
  test:
    attributes: "RAraki/data/derived_attrs/assembled_RA/attrs_cara_and_gages2+climate+morph+padcat+cluster.csv"
experiment_name: "test"
filter_by_cluster:
  run: true
  name: 1
settings:
  seed: 0
  ntree: 10
  num_folds: 3
  eval_metric: "RMSE"
parallel:
  nCores: 16
sigs_predict:
  - TotalRR
  - RR_Seasonality
attrs_of_interest:
  - ele_mt_sav
  - area
  - sgr_dk_sav
  - for_pc_sse
  - crp_pc_sse
  - pst_pc_sse
  - ire_pc_sse
  - prm_pc_sse
  - pac_pc_sse
  - isowet_areafrac
